Biograf_Booking_Web/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biograf_Booking_Web.Controllers
{
    public class MessagesController : Controller
    {
        // GET: Message
        public ActionResult SeatError()
        {
            return View();
        }

        public ActionResult LogInError()
        {
            return View();
        }

        public ActionResult RegistrerError()
        {
            return View();
        }

        public ActionResult ReservationError()
        {
            return View();
        }

        public ActionResult Confirmation()
        {
            return View();
        }
    }
}

Biograf_Booking_Web/Controllers/MovieController.cs
using Biograf_Booking_Web.Models;
using Biograf_Booking_Web.Service;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biograf_Booking_Web.Controllers
{
    public class MovieController : Controller
    {
        private MovieService MovService = new MovieService();

        // GET: Movies
        public ActionResult ShowTimes(int id)
        {
            Movie m = MovService.GetMovie(id);
            Session["MovieId"] = m.MovieId;
            Session["Title"] = m.Title;
            return View(m);
        }
        public ActionResult Movies()
        {
            return View(MovService.GetMovies());
        }
        public ActionResult ShowMovies()
        {
            return View(MovService.GetMovies());
        }

    }
}

Biograf_Booking_Web/Controllers/ReservationController.cs
using Biograf_Booking_Web.Models;
using Biograf_Booking_Web.Service;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biograf_Booking_Web.Controllers
{
    public class ReservationController : Controller
    {
        private ReservationService ResService = new ReservationService();
        private SeatService sService = new SeatService();

        public ActionResult SeatBooking()
        {
            if (Session["CustomerId"] != null)
            {
                return View(sService.FindSeatsByHallId(1));
            }
            else
            {
                return RedirectToAction("Login", "Customer");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SeatBooking(Reservation r, string reservedSeats)
        {
            r.Seats = new List<Seat>();
            string[] foundReservedSeats = null; ;
            // if reservation string (hidden field in form) has real content
            if (!string.IsNullOrWhiteSpace(reservedSeats))
            {
                Session["BookedSeats"] = reservedSeats;
                foundReservedSeats = reservedSeats.Split(':');
            }
            // Handle the reservations in some way
            if (foundReservedSeats != null && foundReservedSeats.Length > 0)
            {

                foreach (var aReservedSeat in foundReservedSeats)
                {
                    if (int.TryParse(aReservedSeat.ToString(), out int seatNum))
                    {

                        Seat s = new Seat();
                        s.SeatId = seatNum;
                        r.Seats.Add(s);
                    }
                }
            }
            else
            {
                // what to do if no reservations
                return RedirectToAction("SeatError", "Messages", new { area = "" });

            }

            r.Time = 1500;
            r.MovieId = Int32.Parse(Session["MovieId"].ToString());
            r.Date = DateTime.Now;
            r.CustomerId = Int32.Parse(Session["CustomerId"].ToString());

            if (ResService.InsertReservation(r) == false)
            {
                return RedirectToAction("ReservationError", "Messages", new { area = "" });
            }
            else
            {
                return RedirectToAction("Confirmation", "Messages", new { area = "" });
            }


        }


    }
}

Biograf_Booking_Web/Views/Messages/Confirmation.cshtml
@model Biograf_Booking_Web.Models.Reservation

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Confirmation</title>
</head>
<body style="background-color:dimgrey">
    <div>
        <h4>Tillykke din reservation er gået igennem</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.Label("Fornavn :", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DisplayName(Session["FName"].ToString())
            </dt>

            <dt>
                @Html.Label("Efternavn :", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DisplayName(Session["LName"].ToString())
            </dt>

            <dt>
                @Html.Label("Mobil Nr.", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DisplayText(Session["PhoneNo"].ToString())
            </dt>

            <dt>
                @Html.Label("Film: ", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DisplayName(Session["Title"].ToString())
            </dt>

            <dt>
                @Html.Label("Sæder ", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DisplayName(Session["BookedSeats"].ToString())
            </dt>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Tilbage", "ShowMovies", "Movie")
    </p>
</body>
</html>

Biograf_Booking_Web/Views/Messages/ReservationError.cshtml
@{
    ViewBag.Title = "Reservationsfejl";
}



@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ReservationError</title>
</head>
<body style="background-color:dimgrey">
    <div>
        @Html.Label("Din reservation gik desværre ikke igennem, prøv igen")
    </div>
    <p>
        @Html.ActionLink("Tilbage","SeatBooking","Movie")
    </p>
</body>
</html>

Biograf_Booking_Web/Views/Messages/SeatError.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sæde fejl</title>
</head>
<body style="background-color:dimgrey">
    <div>
        @Html.Label("Du mangler at markere et eller flere sæder, prøv igen")
    </div>

    <p>
        @Html.ActionLink("Tilbage", "SeatBooking", "Reservation")
    </p>
</body>
</html>