Biograf_Booking_Web/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Biograf_Booking_Web.Models
{
    public class Movie
    {
        
        public string Title { get; set; }

        public string Resume { get; set; }
       
        [DataType(DataType.Date)]
        public DateTime PremiereDate { get; set; }

        public string Genre { get; set; }

        public int MovieId { get; set; }

        public int MovieLength { get; set; }
        public string ImagePath { get; set; }

    }
}

Biograf_Booking_Web/Controllers/CustomerController.cs
using Biograf_Booking_Web.Models;
using Biograf_Booking_Web.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biograf_Booking_Web.Controllers
{
    public class CustomerController : Controller
    {
        private CustomerService cService = new CustomerService();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(Customer c)
        {

            if (ModelState.IsValidField("Email") && ModelState.IsValidField("Password"))
            {
                var obj = cService.Login(c.Email, c.Password);
                Session["CustomerId"] = obj.CustomerId.ToString();
                Session["PhoneNo"] = obj.PhoneNo.ToString();
                Session["FName"] = obj.FName.ToString();
                Session["LName"] = obj.LName.ToString();
                return RedirectToAction("SeatBooking", "Reservation");
            }
            return View();
        }

        public ActionResult Registrer()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrer(Customer c)
        {
            if (ModelState.IsValid)
            {
                cService.InsertCustomer(c);
                c = cService.Login(c.Email, c.Password);
                Session["CustomerId"] = c.CustomerId.ToString();
                Session["FName"] = c.FName;
                Session["LName"] = c.LName;
                Session["PhoneNo"] = c.PhoneNo.ToString();

                return RedirectToAction("SeatBooking", "Reservation");
            }
            return View();
        }
    }
}

Biograf_Booking_Web/Controllers/MovieController.cs
using Biograf_Booking_Web.Models;
using Biograf_Booking_Web.Service;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biograf_Booking_Web.Controllers
{
    public class MovieController : Controller
    {
        private MovieService MovService = new MovieService();

        // GET: Movies
        public ActionResult ShowTimes(int id)
        {
            Movie m = MovService.GetMovie(id);
            Session["MovieId"] = m.MovieId;
            Session["Title"] = m.Title;
            return View(m);
        }
        public ActionResult Movies()
        {
            return View(MovService.GetMovies());
        }
        public ActionResult ShowMovies()
        {
            return View(MovService.GetMovies());
        }

    }
}

Biograf_Booking_Web/Views/Movie/Movies.cshtml
@model IEnumerable<Biograf_Booking_Web.Models.Movie>

@{
    ViewBag.Title = "Movies";
}

<h2>Movies</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieLength)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PremiereDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Resume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieLength)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PremiereDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MovieId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MovieId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MovieId })
        </td>
    </tr>
}

</table>

Biograf_Booking_Web/Views/Movie/MoviesTest.cshtml
@model IEnumerable<Biograf_Booking_Web.Models.Movie>

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Biobooking.dk</title>
</head>
<body style="background-color:dimgrey">

    <header>
        <h1 style="font-family:Cambria;">Film menu </h1>
    </header>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>


        A {
            text-decoration: none;
        }

        .row {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        .container {
            position: relative;
            width: 360px;
            height: 534px;
        }

        .image {
            opacity: 1;
            display: block;
            transition: .5s ease;
            backface-visibility: hidden;
        }

        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 30%;
            left: 0;
            right: 0;
            width: 100%;
            text-align: center;
        }

        .container:hover .image {
            opacity: 0.5;
        }

        .container:hover .middle {
            opacity: 1;
        }

        .text {
            background-color: #4CAF50;
            color: white;
            font-size: 24px;
            padding: 16px 0;
            margin: auto;
            width: 100px;
        }
    </style>




    <div class="row">

        @foreach (var item in Model)
        {
            <div class="container">
                <div class="img">
                    <img src=@Html.DisplayFor(modelItem => item.ImagePath) alt=@Html.DisplayFor(modelItem => item.Title) class="image">
                    <div class="middle">
                        <a href="JokerTid.html" />
                        
                        <div class="text">Book nu</div>
                    </div>
                </div>
            </div>
        }
        </div>

</body>
</html>

Biograf_Booking_Web/Views/Movie/Registrer.cshtml
@model Biograf_Booking_Web.Models.Customer

@{
    ViewBag.Title = "Registrer";
}

<h2>Du kan Registrer her</h2>
<body style="background-color:dimgrey">

    @using (Html.BeginForm("Registrer", "Movie", FormMethod.Post))
    {

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-horizontal">
            <h4>Registrer her</h4>
            <hr />

            <div class="form-group">
                @Html.Label("Fornavn", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Efternavn", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Mobil nr", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Adgangskode", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Registrer" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <p>
        @Html.ActionLink("Tilbage til login","Login", "Movie")
    </p>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biograf_Booking_Web/Views/Movie/SeatBooking.cshtml
@model IList<Biograf_Booking_Web.Models.Seat>
<!DOCTYPE html>

<html>
<head>
    <title>Sæde reservation</title>
    <link href="~/Content/StyleSheetSeats.css" rel="stylesheet" type="text/css" />
</head>
<body style="background-color:dimgrey">
    >

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <input type="hidden" id="reservedSeats" name="reservedSeats" value="">
        <div class="cinema">
            <div class="form-group">
                <ol class="allSeats">
                    <li class="row row--1">
                        <ol class="seats" type="A">
                            @for (int i = 1; i < 13; i++)
                            {

                                var booked = "";
                                var v = i - 1;

                                if (Model[v].booked)
                                {
                                    booked = "disabled";
                                }
                                <li class="seat">
                                    <input type="checkbox" id=@i value="0" name="seat" onclick="seatchange(@i)" @booked />
                                    <label for="@i">@i</label>
                                </li>

                            }
                        </ol>
                    </li>

                    <li class="row row--2">
                        <ol class="seats" type="A">
                            @for (int i = 13; i < 25; i++)
                            {

                                var booked = "";
                                var v = i - 1;

                                if (Model[v].booked)
                                {
                                    booked = "disabled";
                                }
                                <li class="seat">
                                    <input type="checkbox" id=@i value="0" name="seat" onclick="seatchange(@i)" @booked />
                                    <label for="@i">@i</label>
                                </li>

                            }
                        </ol>
                    </li>
                    <li class="row row--3">
                        <ol class="seats" type="A">
                            @for (int i = 25; i < 37; i++)
                            {

                                var booked = "";
                                var v = i - 1;

                                if (Model[v].booked)
                                {
                                    booked = "disabled";
                                }
                                <li class="seat">
                                    <input type="checkbox" id=@i value="0" name="seat" onclick="seatchange(@i)" @booked />
                                    <label for="@i">@i</label>
                                </li>

                            }
                        </ol>
                    </li>
                    <li class="row row--4">
                        <ol class="seats" type="A">
                            @for (int i = 37; i < 49; i++)
                            {

                                var booked = "";
                                var v = i - 1;

                                if (Model[v].booked)
                                {
                                    booked = "disabled";
                                }
                                <li class="seat">
                                    <input type="checkbox" id=@i value="0" name="seat" onclick="seatchange(@i)" @booked />
                                    <label for="@i">@i</label>
                                </li>

                            }
                        </ol>
                    </li>
                    <li class="row row--5">
                        <ol class="seats" type="A">
                            @for (int i = 49; i < 61; i++)
                            {

                                var booked = "";
                                var v = i - 1;

                                if (Model[v].booked)
                                {
                                    booked = "disabled";
                                }
                                <li class="seat">
                                    <input type="checkbox" id=@i value="0" name="seat" onclick="seatchange(@i)" @booked />
                                    <label for="@i">@i</label>
                                </li>

                            }
                        </ol>
                    </li>
                    <li class="row row--6">
                        <ol class="seats" type="A">
                            @for (int i = 61; i < 73; i++)
                            {

                                var booked = "";
                                var v = i - 1;

                                if (Model[v].booked)
                                {
                                    booked = "disabled";
                                }
                                <li class="seat">
                                    <input type="checkbox" id=@i value="0" name="seat" onclick="seatchange(@i)" @booked />
                                    <label for="@i">@i</label>
                                </li>

                            }
                        </ol>
                    </li>
                    <li class="row row--7">
                        <ol class="seats" type="A">
                            @for (int i = 73; i < 85; i++)
                            {

                                var booked = "";
                                var v = i - 1;

                                if (Model[v].booked)
                                {
                                    booked = "disabled";
                                }
                                <li class="seat">
                                    <input type="checkbox" id=@i value="0" name="seat" onclick="seatchange(@i)" @booked />
                                    <label for="@i">@i</label>
                                </li>

                            }
                        </ol>
                    </li>
                </ol>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    }
    <script src="~/Javascript/MovieDynamics.js"></script>
</body>
</html>

Biograf_Booking_Web/Views/Movie/ShowMovies.cshtml
@model IEnumerable<Biograf_Booking_Web.Models.Movie>

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Biobooking.dk</title>
</head>
<body style="background-color:dimgrey">

    <header>
        <h1 style="font-family:Cambria;">Film menu </h1>
    </header>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>


        A {
            text-decoration: none;
        }

        .row {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        .container {
            position: relative;
            width: 360px;
            height: 534px;
        }

        .image {
            opacity: 1;
            display: block;
            transition: .5s ease;
            backface-visibility: hidden;
        }

        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 30%;
            left: 0;
            right: 0;
            width: 100%;
            text-align: center;
        }

        .container:hover .image {
            opacity: 0.5;
        }

        .container:hover .middle {
            opacity: 1;
        }

        .text {
            background-color: #4CAF50;
            color: white;
            font-size: 24px;
            padding: 16px 0;
            margin: auto;
            width: 100px;
        }
    </style>




    <div class="row">

        @foreach (var item in Model)
        {
            <div class="container">
                <div class="img">
                    <img src=@Html.DisplayFor(modelItem => item.ImagePath) alt=@Html.DisplayFor(modelItem => item.Title) class="image">
                    <div class="middle">
                        <a href="ShowTimes" />
                        
                        <div class="text">@Html.ActionLink("Book nu", "ShowTimes", new { id = item.MovieId }) </div>
                    </div>
                </div>
            </div>
        }
        </div>

</body>
</html>

Biograf_Booking_Web/Views/Movie/ShowTimes.cshtml
@model Biograf_Booking_Web.Models.Movie
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Film Detaljer</title>
</head>
    <body style="background-color:dimgrey">
        <h1 style="font-family:Cambria;">Bestil ledige tider</h1>

        <style>
            .info {
                position: absolute;
                top: 140px;
                right: 1180px;
                width: 300px;
            }

            .time {
                position: absolute;
                top: 260px;
                right: 1180px;
                width: 300px;
            }
        </style>

        <nav>
            <a style="font-family:Cambria; font-size: 30px; color: black;" href="~/Movie/ShowMovies"> Tilbage </a>
        </nav>

        <div class="container">
            <div class="img">
                <img src=@Html.DisplayFor(model => model.ImagePath) alt=@Html.DisplayFor(model => model.Title) class="image">

            </div>
        </div>
        <div class="info">
                    <nav>
                            <a style="font-family:Cambria; background-color: #4CAF50; font-size: 30px; color: black;" href="https://www.imdb.com/title/tt7286456/"> Film information </a>
                    </nav>
                    <br /><br />
                    <h2>Vælg din tid:</h2>
                </div>
        <div class="time">
            <nav>
                @Html.ActionLink("16:00", "LogIn", "Customer", new { Time = 1600, id = Model.MovieId }, null)
            </nav>
            <nav>
                @Html.ActionLink("18:30", "LogIn","Customer", new { Time = 1830, id = Model.MovieId }, null)
            </nav>
            <nav>
                @Html.ActionLink("20:30", "LogIn","Customer", new { Time = 2030, id = Model.MovieId}, null)
            </nav>
           
        </div>
        </body>
</html>